### ISSUE TITLE
Add "is" and "has" operators

### ISSUE THREAD

**Issue by wavebeem** [wavebeem/squiggle#46]
`is` will just be syntax sugar for `Object.is` (with a polyfill)

```
foo is bar
```

`has` will be JS `in` but reversed order

```
foo has "property"
```

**Comment by wavebeem** [comment]
TODO: Any good reason to switch to `has` instead of JS standard `in`?

**Comment by rdenmark** [comment]
What is the argument against implementing both? I understand wanting to support the standard diction of `in`, but find `has` "reads" better.

**Comment by wavebeem** [comment]
@rdenmark This is purely a "style vs familiarity" battle.

`foo is bar` vs `Object.is(foo, bar)`

`foo has "prop"` vs `"prop" in foo`

Both things are worth it in the long run, I think, but make Squiggle larger. I think there's probably enough value here. Especially if Squiggle polyfills Object.is, since Safari and IE don't currently support it.

**Comment by wavebeem** [comment]
Another thought I just had: switching to "has" over "in" makes it so "in" is only used for one thing in the language (declaration scope like `let x = 1 in x`), making it so this confusing thing won't parse:

```
let x = "k" in y in x
```

Two completely different "kinds" of `in` right next to each other... yuck.
