### ISSUE TITLE
Rename "Map" and "List" internally

### ISSUE THREAD

**Issue by wavebeem** [wavebeem/squiggle#47]
I don't think there's any good reason to push "Map" over "Object" or "List" over "Array", so I should change the internal names of those in the code to reflect common JavaScript parlance.

**Comment by rdenmark** [comment]
https://github.com/wavebeem/squiggle/pull/52

**Comment by wavebeem** [comment]
Thanks for the code. Also fyi if you include "Fixes #47" in your commit message, simply merging the branch will close the related issue.
