### ISSUE TITLE
Disallow `has` with anything other than string.

### ISSUE THREAD

**Issue by wavebeem** [wavebeem/squiggle#68]
`has` is implemented in terms of JavaScript's `in` (see `predef.js`).

The implementation `$has` should check to make sure the key being searched for is actually a string, and otherwise throw an error. JavaScript's `in` isn't very picky, and allows silly things like `[] in {"": 1}` to be  `true` because the `[]` gets coerced to a string.

This type coercion violates Squiggle's goals.

**Comment by wavebeem** [comment]
Number should be allowed too. And it should probably be an error to use a non-integer number as key.

**Comment by noahmorrison** [comment]
I messed up the auto-closing feature of github. I said "Closes issue #68" instead of "Closes #68". If my PR completed this issue then you'll have to close it manually.

**Comment by wavebeem** [comment]
Thanks for catching that! I was too busy to look over the issue list and catch it.
