### ISSUE TITLE
Add modulo operator

### ISSUE THREAD

**Issue by wavebeem** [wavebeem/squiggle#81]
Modulo can be useful sometimes, so there should probably be an operator for it. That being said, I'm not a fan of JavaScript's `%` as it's actually a remainder operator. I think Squiggle could use the form `x mod y` and then it's not so weird when it has different semantics from JS. Or it could be omitted entirely and added to a helper library as just a function: `mod(x, y)`.

**Comment by noahmorrison** [comment]
My vote is for ```x mod y``` for modulo, and ```x rem y``` for the standard JS remainder operator.

**Comment by wavebeem** [comment]
Having both could be good, but I'm most likely going with including them as library functions, along with bitwise operators.

```
let {console} = global
let {mood, rem, bitAnd} = require("squiggle/util")
let data = [mod(-5, 4), rem(-5, 4), bitAnd(4, 1)]
in console.log(data)
#=> [3, -1, 5]
```
